baseURL = "https://www.monsty.co"
metaDataFormat = "yaml"
title = "Monsty The Monster Truck"
theme = "blist"
show_reading_time = true
publishDir = "publicTmp"
enableRobotsTXT = true
#googleAnalytics = "G-xxxxxx"
disqusShortname = "relaxedincome"
googleAnalytics = 'G-X0YYFYKK2G'

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = false
#
timeout = 600000
#
[permalinks]
  posts = "/:filename"
  blog = "/:filename"
  page = "/:filename"

[taxonomies]
#  category = 'category'
  tag = 'tags'

[languages]
  [languages.en]
    contentDir = "content/en"
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Hey! I'm Manu Balin"
      introSubtitle = "Author of Bestseller : Monsty The Monster Truck"
      introPhoto = "/tpdne_poster.png"
      logo = "/blist-logo.png"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1
    [[languages.en.menu.main]]
        name = "Books by Life Lessons"
        url = "tags"
        weight = 2        
#    [[languages.en.menu.main]]
#        name = "Category"
#        url = "category"
#        weight = 2
#    [[languages.en.menu.main]]
#        name = "Subscribe"
#        url = "page/subscribe"
#        weight = 4

#    [[languages.en.menu.main]]
#        name = "About"
#        url = "page/about/"
#        weight = 3

#    [[languages.en.menu.main]]
#        name = "Top Post"
#        url = "/en/blog/emoji-support/"
#        weight = 4

[params]
  darkModeToggle = true
  enableSearch = true

  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  copyright = "Copyright © 2023 - Monsty.co · All rights reserved"
  favicon = "/favicon.svg"
#
  ascentColor = "bg-blue-100"
#
  frontBundle = "blog"
#
  hideMeta = false
#
  hideOtherLanguages = true
#
  toc = false
#
  hidePageThumbnail = false


  [[params.hugoLeaflet.css]]
  href = "https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
  crossorigin = ""

    [params.hugoLeaflet.css.params]
    integrity = "sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="

  [[params.hugoLeaflet.css]]
  href = "https://unpkg.com/@raruto/leaflet-elevation@1.1.1/dist/leaflet-elevation.css"

  [[params.hugoLeaflet.css]]
  href = "/css/leaflet.extra-markers.min.css"

  [[params.hugoLeaflet.js]]
  src = "https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
  crossorigin = ""

    [params.hugoLeaflet.js.params]
    integrity = "sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="

  [[params.hugoLeaflet.js]]
  src = "/js/leaflet.elevation.js"

  [[params.hugoLeaflet.js]]
  src = "/js/leaflet.hugo.js"

  [[params.hugoLeaflet.js]]
  src = "/js/leaflet.extra-markers.min.js"

# Comments system
[params.comments]
  system = "disqus"
[build]
  writeStats = true
[outputs]
  home = ["HTML", "RSS", "JSON"]
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    unsafe = true
#
[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"
